import {initOrbit} from './motion.mjs';
import {services} from './data.mjs';
const root=document.documentElement;let reduced=matchMedia('(prefers-reduced-motion: reduce)');let toastTimer;
export function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500)}
function updateMotion(){const paused=root.dataset.motion==='paused';const label=paused?'Resume motion':'Pause motion';document.querySelector('.motion-toggle').setAttribute('aria-label',label);document.querySelector('.motion-toggle').setAttribute('aria-pressed',String(paused));document.querySelector('.motion-toggle span').textContent=paused?'▷':'Ⅱ';document.querySelector('.footer-motion').textContent=label;document.dispatchEvent(new Event('cat:motion'))}
function toggleMotion(){root.dataset.motion=root.dataset.motion==='paused'?'on':'paused';try{localStorage.setItem('catstronaut-motion',root.dataset.motion)}catch{}updateMotion()}
document.querySelector('.motion-toggle').addEventListener('click',toggleMotion);document.querySelector('.footer-motion').addEventListener('click',toggleMotion);reduced.addEventListener('change',e=>{let saved;try{saved=localStorage.getItem('catstronaut-motion')}catch{}if(!saved){root.dataset.motion=e.matches?'paused':'on';updateMotion()}});updateMotion();
const dialog=document.querySelector('#mobile-menu'),menu=document.querySelector('.menu-toggle');menu.addEventListener('click',()=>{dialog.showModal();menu.setAttribute('aria-expanded','true');document.body.style.overflow='hidden'});document.querySelector('[data-close-menu]').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{menu.setAttribute('aria-expanded','false');document.body.style.overflow='';menu.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog&&e.clientY>dialog.getBoundingClientRect().bottom)dialog.close()});window.addEventListener('resize',()=>{if(innerWidth>900&&dialog.open)dialog.close()});
const reveal=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in-view');reveal.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('[data-reveal]').forEach(el=>reveal.observe(el));root.classList.add('motion-enabled');initOrbit();
document.querySelectorAll('[data-pet]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-pet]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.querySelector('#pet-copy').textContent={all:'From sofa astronauts to park pioneers, we make room for every kind of companion. Thoughtful care, clear conversations and a pace that feels right.',cat:'For the window-watchers and quiet adventurers. A softer arrival, a little more patience, and care that makes room for their feline ways.',dog:'For the park pioneers and professional sofa-testers. From a first hello to the golden chapters, we make space for every wag and every question.'}[b.dataset.pet]}));
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));let count=0;document.querySelectorAll('.service-row').forEach(row=>{const s=services.find(x=>row.getAttribute('href')===`/care/${x.id}`);const show=b.dataset.filter==='all'||s.pets.includes(b.dataset.filter);row.hidden=!show;if(show)count++});document.querySelector('#service-count').textContent=`${count} kinds of care`}));
const checklist=[...document.querySelectorAll('[data-check]')];if(checklist.length){let stored=[];try{const value=JSON.parse(localStorage.getItem('catstronaut-checklist')||'[]');if(Array.isArray(value))stored=value}catch{};const sync=()=>{document.querySelector('#checklist-count').textContent=`${checklist.filter(x=>x.checked).length} of ${checklist.length} ready`};checklist.forEach(el=>{el.checked=stored.includes(el.dataset.check);el.addEventListener('change',()=>{try{localStorage.setItem('catstronaut-checklist',JSON.stringify(checklist.filter(x=>x.checked).map(x=>x.dataset.check)))}catch{toast('Your browser could not save this checklist.')}sync()})});document.querySelector('#reset-checklist').addEventListener('click',()=>{checklist.forEach(x=>x.checked=false);try{localStorage.removeItem('catstronaut-checklist')}catch{}sync()});sync()}
if(document.querySelector('#booking-app')||document.querySelector('#visits-app'))import('./booking.mjs').then(m=>m.initBooking()).catch(()=>toast('The booking tools could not load. Please refresh to try again.'));
