import {services} from './data.mjs';
import {VISITS_KEY,times,datesFrom,parseDate,readVisits,validateBooking,calendarText} from './booking-domain.mjs';
import {toast} from './app.mjs';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const arrow='<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" stroke-width="1.7"/></svg>';
const dateLabel=d=>parseDate(d).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});
function storage(){try{return localStorage}catch{return{getItem:()=>null,setItem:()=>{throw Error('Storage unavailable')}}}}
const getVisits=()=>readVisits(storage()).filter(v=>services.some(s=>s.id===v.service));
const field=(label,name,type='text',extra='')=>`<label class="field">${label}<input name="${name}" type="${type}" ${extra}></label>`;
function download(v){const s=services.find(s=>s.id===v.service);const blob=new Blob([calendarText(v,s)],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='catstronaut-demo-visit.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('Demo calendar reminder downloaded.')}
export function initBooking(){if(document.querySelector('#booking-app'))booking();if(document.querySelector('#visits-app'))visits();}
function booking(){const host=document.querySelector('#booking-step'),sum=document.querySelector('#booking-summary'),params=new URLSearchParams(location.search),edit=getVisits().find(v=>v.id===params.get('edit'));let state={service:services.some(s=>s.id===params.get('service'))?params.get('service'):'',date:'',time:'',pet:'',species:'',stage:'',consent:false,...edit};let step=0;let saving=false;
 const service=()=>services.find(s=>s.id===state.service);
 function summary(){const s=service();sum.innerHTML=s?`<h2>${s.name}</h2><dl><dt>Consultation</dt><dd>${s.duration} minutes · $${s.price}</dd>${state.date?`<dt>Date & time</dt><dd>${dateLabel(state.date)}${state.time?` · ${state.time}`:''}</dd>`:''}${state.pet?`<dt>Companion</dt><dd>${escape(state.pet)}${state.species?` · ${escape(state.species)}`:''}</dd>`:''}</dl>`:'<h2>A good start.</h2><p>Your choices will appear here.</p>'}
 function focusHeading(){host.querySelector('h2')?.focus({preventScroll:true});if(document.querySelector('.booking-steps').getBoundingClientRect().top<90)document.querySelector('.booking-steps').scrollIntoView({block:'start',behavior:'instant'})}
 function error(message){let el=host.querySelector('.form-error');if(!el){el=document.createElement('p');el.className='form-error';el.setAttribute('role','alert');host.prepend(el)}el.textContent=message;el.scrollIntoView({block:'nearest',behavior:'instant'})}
 function buttons(next='Continue'){return `<div class="booking-buttons">${step>0?'<button class="back" data-back>← Back</button>':'<span></span>'}<button class="button" data-next>${next}${arrow}</button></div>`}
 function render(focus=true){document.querySelectorAll('.booking-steps li').forEach((li,i)=>{if(i===step)li.setAttribute('aria-current','step');else li.removeAttribute('aria-current')});summary();
 if(step===0){host.innerHTML=`<h2 tabindex="-1">What brings you in?</h2><p>Choose a starting point. Sample fees are in USD.</p><div class="booking-choice">${services.map(s=>`<button class="choice" data-service="${s.id}" aria-pressed="${s.id===state.service}"><span aria-hidden="true">${s.icon}</span><span><strong>${s.name}</strong><small>${s.duration} min · $${s.price}</small></span></button>`).join('')}</div>${buttons()}`;host.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>{state.service=b.dataset.service;if(service().pets.length===1)state.species='cat';host.querySelectorAll('[data-service]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));summary()}));}
 if(step===1){const dates=datesFrom();if(!dates.includes(state.date)){state.date='';state.time=''}host.innerHTML=`<h2 tabindex="-1">Find a little time.</h2><p>Sample availability · Times use your device’s local timezone.</p><div class="dates" role="group" aria-label="Available sample dates">${dates.map(d=>{const dt=parseDate(d);return`<button class="date-choice" data-date="${d}" aria-pressed="${d===state.date}" aria-label="${dateLabel(d)}"><span>${dt.toLocaleDateString('en-US',{weekday:'short'})}</span><b>${dt.getDate()}</b><span>${dt.toLocaleDateString('en-US',{month:'short'})}</span></button>`}).join('')}</div><div id="time-options"></div>${buttons()}`;const showTimes=()=>{const el=host.querySelector('#time-options');el.innerHTML=state.date?`<p class="kicker">${dateLabel(state.date)}</p><div class="time-grid" role="group" aria-label="Available sample times">${times.map(t=>{const unavailable=getVisits().some(v=>v.date===state.date&&v.time===t&&v.id!==state.id);return`<button class="time-choice" data-time="${t}" aria-pressed="${t===state.time}" ${unavailable?'disabled':''}>${t}${unavailable?' · saved':''}</button>`}).join('')}</div>`:'<p class="muted">Choose a date to see sample times.</p>';el.querySelectorAll('[data-time]').forEach(b=>b.addEventListener('click',()=>{state.time=b.dataset.time;showTimes();summary()}))};host.querySelectorAll('[data-date]').forEach(b=>b.addEventListener('click',()=>{state.date=b.dataset.date;state.time='';host.querySelectorAll('[data-date]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));showTimes();summary()}));showTimes();}
 if(step===2){host.innerHTML=`<h2 tabindex="-1">Who are we meeting?</h2><p>A few simple details. No contact or clinical information needed.</p><form id="companion-form" novalidate><div class="booking-fields">${field('Companion’s name','pet','text',`required maxlength="50" autocomplete="off" value="${escape(state.pet)}" placeholder="e.g. Luna"`)}<label class="field">Your companion<select name="species" required><option value="">Choose a companion</option><option value="cat" ${state.species==='cat'?'selected':''}>Cat</option>${service().pets.includes('dog')?`<option value="dog" ${state.species==='dog'?'selected':''}>Dog</option>`:''}</select></label><label class="field wide">Life stage <span class="tiny">Optional</span><select name="stage"><option value="">Prefer not to say</option>${['Puppy or kitten','Adult','Senior'].map(s=>`<option ${state.stage===s?'selected':''}>${s}</option>`).join('')}</select></label></div>${buttons('Review visit')}</form>`;host.querySelector('form').addEventListener('submit',e=>e.preventDefault());host.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',()=>{state[el.name]=el.value;summary()}));}
 if(step===3){const s=service();host.innerHTML=`<h2 tabindex="-1">One last look.</h2><p>${edit?'Review your updated demo visit.':'Here is the visit you are about to save.'}</p><dl class="review-lines"><div><dt>Companion</dt><dd>${escape(state.pet)} · ${escape(state.species)}</dd></div><div><dt>Care</dt><dd>${s.name}</dd></div><div><dt>When</dt><dd>${dateLabel(state.date)}<br>${state.time} · ${s.duration} minutes</dd></div><div><dt>Sample fee</dt><dd>$${s.price} USD<br><small>No payment taken</small></dd></div></dl><label class="confirm-check"><input type="checkbox" name="consent" ${state.consent?'checked':''}><span>I understand this saves a demo visit on this device. It does not reserve a real appointment or contact a clinic.</span></label>${buttons(edit?'Save changes':'Save demo visit')}`;host.querySelector('[name=consent]').addEventListener('change',e=>state.consent=e.target.checked)}
 host.querySelector('[data-back]')?.addEventListener('click',e=>{e.preventDefault();step--;render()});host.querySelector('[data-next]')?.addEventListener('click',e=>{e.preventDefault();next()});if(focus)focusHeading();}
 function next(){if(step===0&&!service())return error('Choose a care option to continue.');if(step===1&&(!state.date||!state.time))return error('Choose both a sample date and time.');if(step===2){state.pet=state.pet.trim();if(!state.pet||state.pet.length>50)return error('Enter a companion’s name of 1–50 characters.');if(!state.species)return error('Choose cat or dog.');if(!service().pets.includes(state.species))return error('Choose a companion supported by this service.')}if(step<3){step++;render();return}save()}
 function save(){if(saving)return;const all=getVisits(),validation=validateBooking(state,services,all);if(validation)return error(validation);if(all.length>=50&&!edit)return error('Remove a saved demo visit before adding another.');saving=true;const v={id:state.id||crypto.randomUUID(),service:state.service,date:state.date,time:state.time,pet:state.pet,species:state.species,stage:state.stage,createdAt:edit?.createdAt||new Date().toISOString()};try{storage().setItem(VISITS_KEY,JSON.stringify([v,...all.filter(x=>x.id!==v.id)]))}catch{saving=false;return error('This browser cannot save visits. Enable site storage or try another browser; no visit has been saved.')};host.innerHTML=`<div class="success-icon" aria-hidden="true">✓</div><h2 tabindex="-1">${edit?'A new time. Same little hello.':'All set for a little hello.'}</h2><p>Your demo visit for <strong>${escape(v.pet)}</strong> is saved on this device.</p><dl class="review-lines"><div><dt>Sample visit</dt><dd>${service().name}<br>${dateLabel(v.date)} · ${v.time}</dd></div></dl><p class="demo-banner">No real appointment was reserved. For veterinary care, contact an actual clinic.</p><div class="success-actions"><button class="button" id="calendar-download">Download reminder ${arrow}</button><a class="button outline" href="/my-visits">My visits ${arrow}</a></div>`;host.querySelector('#calendar-download').addEventListener('click',()=>download(v));focusHeading();toast(edit?'Demo visit updated.':'Demo visit saved on this device.')}
 render(false);
}
function visits(){const host=document.querySelector('#visits-app');function render(){const all=getVisits().sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));if(!all.length){host.innerHTML=`<div class="empty-visits"><span aria-hidden="true">✳</span><h2>No little hellos planned. Yet.</h2><p>Try the demo booking experience and your saved visits will appear here.</p><a class="button" href="/book">Plan a demo visit ${arrow}</a></div>`;return}host.innerHTML=all.map(v=>{const s=services.find(s=>s.id===v.service),d=parseDate(v.date);return`<article class="saved-visit" data-visit="${v.id}"><div class="saved-date"><strong>${d.getDate()}</strong><span>${d.toLocaleDateString('en-US',{month:'short'})}</span></div><div><h2>${escape(v.pet)}’s little visit.</h2><p>${s.name}<br>${dateLabel(v.date)} · ${v.time} · ${s.duration} min</p><small>DEMO ONLY · No real appointment reserved</small></div><div class="visit-actions"><button data-download="${v.id}">Calendar reminder ↓</button><a href="/book?edit=${v.id}">Reschedule ↗</a><button data-delete="${v.id}">Remove visit</button></div></article>`}).join('');host.querySelectorAll('[data-download]').forEach(b=>b.addEventListener('click',()=>download(all.find(v=>v.id===b.dataset.download))));host.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',()=>{const card=b.closest('article');if(card.querySelector('.delete-confirm'))return;const box=document.createElement('div');box.className='delete-confirm';box.innerHTML='<p>Remove this demo visit from this device?</p><button data-confirm-delete>Yes, remove visit</button><button data-cancel-delete>Keep visit</button>';card.append(box);box.querySelector('[data-cancel-delete]').addEventListener('click',()=>{box.remove();b.focus()});box.querySelector('[data-confirm-delete]').addEventListener('click',()=>{try{storage().setItem(VISITS_KEY,JSON.stringify(getVisits().filter(v=>v.id!==b.dataset.delete)));render();toast('Demo visit removed.')}catch{toast('Could not remove the visit. Please try again.')}});box.querySelector('[data-cancel-delete]').focus()}));}
 render();window.addEventListener('storage',render);
}
