export const VISITS_KEY='catstronaut-demo-visits-v1';
export const times=['08:30','09:30','11:00','12:00','14:00','15:30'];
export const localDate=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export function datesFrom(now=new Date()){const arr=[];const d=new Date(now);d.setHours(12,0,0,0);while(arr.length<8){d.setDate(d.getDate()+1);if(d.getDay()!==0)arr.push(localDate(d))}return arr;}
export const parseDate=s=>new Date(`${s}T12:00:00`);
export function validVisit(v){return !!v&&typeof v.id==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(v.id)&&typeof v.service==='string'&&/^[a-z-]+$/.test(v.service)&&typeof v.pet==='string'&&v.pet.trim().length>0&&v.pet.length<=50&&['cat','dog'].includes(v.species)&&typeof v.date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v.date)&&!Number.isNaN(parseDate(v.date).getTime())&&times.includes(v.time)}
export function readVisits(store){try{const value=JSON.parse(store.getItem(VISITS_KEY)||'[]');return Array.isArray(value)?value.filter(validVisit).slice(0,50):[]}catch{return[]}}
export function validateBooking(s,services,visits=[],now=new Date()){const service=services.find(x=>x.id===s.service);if(!service)return'Choose a care option.';if(!datesFrom(now).includes(s.date))return'Choose an available future date.';if(!times.includes(s.time))return'Choose an available time.';if(visits.some(v=>v.date===s.date&&v.time===s.time&&v.id!==s.id))return'That sample time is already saved on this device. Choose another time.';if(!s.pet?.trim()||s.pet.trim().length>50)return'Enter a companion’s name of 1–50 characters.';if(!['cat','dog'].includes(s.species))return'Choose cat or dog.';if(!service.pets.includes(s.species))return'This care option is for cats. Choose another service for a dog.';if(!s.consent)return'Please confirm that you understand this is a demo visit.';return''}
export function calendarText(v,service){const day=v.date.replaceAll('-',''),start=v.time.replace(':','')+'00';const [hh,mm]=v.time.split(':').map(Number);const endMin=hh*60+mm+service.duration,end=String(Math.floor(endMin/60)).padStart(2,'0')+String(endMin%60).padStart(2,'0')+'00';const safe=s=>String(s).replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(',','\\,').replaceAll(';','\\;').replaceAll('\r','');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Catstronaut//Demo visits//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:${v.id}@catstronaut-demo`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART:${day}T${start}`,`DTEND:${day}T${end}`,`SUMMARY:${safe(`DEMO: ${v.pet} — ${service.name}`)}`,'DESCRIPTION:Sample visit only. No real clinical appointment is reserved. Times use your local calendar timezone.','STATUS:TENTATIVE','END:VEVENT','END:VCALENDAR',''].join('\r\n')}
