export const services=[
 {id:'wellness',name:'Everyday wellness',tag:'The whole picture',icon:'✳',desc:'Time to ask questions. Space to get comfortable. A thoughtful look at your companion’s everyday health.',detail:'A wellness visit starts with listening: what has changed, what feels normal, and what you want to understand. We build the conversation around your pet’s age, lifestyle and personality.',items:['A nose-to-tail examination','A conversation about food, activity and behaviour','An individual vaccination and parasite-prevention discussion','A written plan for what comes next'],pets:['cat','dog'],duration:30,price:85},
 {id:'dental',name:'Dental care',tag:'A reason to smile',icon:'✧',desc:'From a first look to a considered treatment plan. Looking after the little things behind a big smile.',detail:'Oral health is part of whole-pet health. Start with a consultation to discuss your pet’s mouth, comfort and habits. Any further assessment or procedure is explained and agreed separately.',items:['An initial oral assessment','A discussion of any recommended investigations','Clear estimates before treatment','Practical home-care guidance from the veterinary team'],pets:['cat','dog'],duration:30,price:85},
 {id:'new-explorers',name:'Puppies & kittens',tag:'A very good beginning',icon:'↗',desc:'For the tiny new arrival and every question that comes with them. Get your bearings, together.',detail:'Bringing a new companion home is a big moment. This longer first visit gives you room to talk through routines, preventive care and the questions you have been saving up.',items:['A first health examination','An individual preventive-care plan','A conversation about settling in','Time for new-pet questions'],pets:['cat','dog'],duration:45,price:105},
 {id:'cat-care',name:'A little more cat',tag:'On their terms',icon:'☾',desc:'Quieter arrivals, gentle handling and a little more patience. Because cats have their own way of doing things.',detail:'A cat’s experience matters from the carrier to the consultation room. Our approach makes room for pauses, familiar comforts and a conversation about what helps your cat feel secure.',items:['A quieter consultation setting','A pace shaped around your cat','Discussion of carrier and travel preparation','An individual care plan'],pets:['cat'],duration:30,price:85},
 {id:'diagnostics',name:'Answers & next steps',tag:'Clarity, with care',icon:'⊕',desc:'When something feels different, start a conversation. We explain the options before deciding what comes next.',detail:'A consultation helps the veterinary team understand your concerns and decide whether further investigation is appropriate. Tests are recommended for a reason, with costs and next steps discussed first.',items:['A conversation about the changes you have noticed','A physical examination','An explanation of recommended tests and costs','A plan for discussing results'],pets:['cat','dog'],duration:40,price:95},
 {id:'senior-care',name:'The golden chapters',tag:'Still so much to explore',icon:'☼',desc:'Thoughtful check-ins for familiar faces. Making room for changing needs and the routines they love.',detail:'Later-life care starts with understanding your companion’s day-to-day life. Tell us about the small changes as well as the big ones, so the conversation stays focused on their comfort and needs.',items:['A review of daily routines and recent changes','An examination tailored to your companion','Discussion of appropriate screening options','A shared plan for follow-up'],pets:['cat','dog'],duration:40,price:95}
];
export const articles=[
 {id:'first-visit',title:'A softer landing at the vet.',category:'First visits',image:'care',intro:'A few thoughtful preparations can make the day feel less unfamiliar—for both of you.',sections:[['Before you arrive','Gather previous health records, a list of any medications or supplements, and your questions. Note the changes you want to discuss. Ask the clinic about preparation specific to your appointment.'],['Bring a little familiarity','A familiar blanket or toy can help make the setting feel less strange. Use a secure carrier for cats and a suitable lead for dogs. Tell the team in advance if travel or waiting rooms are difficult for your pet.'],['Make room for the conversation','Share what everyday life looks like: eating, sleeping, play and anything that has changed. You do not need to know the right terminology. Your observations are a useful starting point.']]},
 {id:'new-companion',title:'New paws. New possibilities.',category:'New companions',image:'orbit',intro:'The first chapter together is full of discoveries. Start with a routine, a safe space and a conversation.',sections:[['Build a familiar starting point','Set up a quiet resting place, suitable food and water bowls, and a safe way to travel before your new companion arrives. Ask their previous carer about established routines.'],['Get to know your companion','Give them time to explore and settle. Keep notes on questions about feeding, activity or behaviour to discuss with a veterinary professional. Individual needs vary.'],['Plan the first appointment','Bring any adoption, vaccination and health records you have. Your veterinary team can help plan appropriate preventive care for your pet’s age and circumstances.']]},
 {id:'dental-conversation',title:'Small teeth. Big conversation.',category:'Everyday care',image:'care',intro:'Your pet’s mouth deserves a place in their regular health conversation.',sections:[['Start with a professional assessment','A veterinarian can assess oral health and discuss whether further examination or treatment is needed. Appearance alone does not tell the full story.'],['Ask about home care','Ask your veterinary team which home-care approach and products are appropriate for your individual pet. Introduce any routine using their guidance.'],['Know your next step','If you notice changes in eating, comfort or behaviour, contact a veterinary professional. A web article cannot assess your pet or replace an examination.']],source:'https://www.avma.org/resources-tools/pet-owners/petcare/pet-dental-care'}
];
export const faqs=[['Do you see both cats and dogs?','Yes. Catstronaut’s concept care journeys cover cats and dogs, from first visits to later-life check-ins. Other species need an appropriately experienced veterinary practice.'],['Can I book here?','You can explore the complete demo appointment flow, save a sample visit on this device, and download a calendar reminder. This concept does not reserve real clinical appointments.'],['What should I bring to a first visit?','Bring available health records, medication details and your questions. Use a secure carrier or suitable lead, and ask your real clinic whether any specific preparation is needed.'],['What if my pet needs urgent help?','Contact a local veterinary practice or emergency veterinary service directly. Do not wait for a website form or a demo appointment.'],['Are the prices real?','Prices and appointment times here are illustrative, shown in USD. In a real clinic, estimates and any additional tests or treatments would be discussed before proceeding.'],['Where is my information saved?','Demo pet names, visit choices and checklist progress are saved only in this browser. No account is created and no appointment is sent to a clinic. You can remove saved visits at any time.']];
