export const clamp=(v,min=0,max=1)=>Math.max(min,Math.min(max,v));
export function scenePose(p,mobile=false){p=clamp(p);return{frame:Math.round(p*95),introOpacity:1-clamp((p-.07)/.2),introX:-p*(mobile?130:280),introZ:-p*1100,introRotate:-p*40,wordOpacity:clamp((p-.2)/.11)*(1-clamp((p-.64)/.12)),wordX:(.49-p)*(mobile?800:2300),wordY:Math.sin(p*Math.PI*2)*(mobile?35:70),wordZ:(p-.5)*750,wordRotate:(.49-p)*110,outroOpacity:clamp((p-.76)/.13),outroY:70*(1-clamp((p-.76)/.2)),chapter:p<.3?0:p<.75?1:2};}
export function subjectFocus(frame){const points=[[0,.55],[24,.50],[42,.31],[64,.58],[80,.53],[95,.50]];for(let i=1;i<points.length;i++){if(frame<=points[i][0]){const [a,x]=points[i-1],[b,y]=points[i];const t=clamp((frame-a)/(b-a));return x+(y-x)*t}}return .5;}
export function initOrbit(){const story=document.querySelector('.orbit-story');if(!story)return;const stage=story.querySelector('.orbit-stage'),canvas=document.querySelector('#orbit-canvas'),ctx=canvas.getContext('2d',{alpha:false}),intro=story.querySelector('.hero-start'),word=story.querySelector('.space-word'),outro=story.querySelector('.orbit-outro'),caption=document.querySelector('#chapter-copy'),count=story.querySelector('.scene-count');if(!ctx)return;
 const cache=new Map(),pending=new Set(),failed=new Set();let raf=0,desired=0,lastDraw=-1,visible=true,mobile=innerWidth<=600,base=innerWidth<=800||navigator.connection?.saveData?'mobile':'desktop',paused=document.documentElement.dataset.motion==='paused',lastP=0,alive=true;const maxCache=18;
 function evict(){if(cache.size<=maxCache)return;const keys=[...cache.keys()].sort((a,b)=>Math.abs(b-desired)-Math.abs(a-desired));while(cache.size>maxCache){const key=keys.shift();cache.get(key)?.close();cache.delete(key)}}
 async function request(index){if(index<0||index>95||cache.has(index)||pending.has(index)||failed.has(index)||pending.size>=3||paused||!visible||!alive)return;pending.add(index);try{const r=await fetch(`/assets/sequence/${base}/frame_${String(index).padStart(3,'0')}.webp`);if(!r.ok)throw Error('Frame unavailable');const bitmap=await createImageBitmap(await r.blob());if(!alive){bitmap.close();return}cache.set(index,bitmap);evict();}catch{failed.add(index);/* Keep the poster or last available frame. */}finally{pending.delete(index);queue()}}
 function draw(index){const im=cache.get(index);if(!im||canvas.width===0)return;const scale=Math.max(canvas.width/im.width,canvas.height/im.height),w=im.width*scale,h=im.height*scale;const offsetX=canvas.height>canvas.width*.8?clamp(canvas.width*.5-w*subjectFocus(index),canvas.width-w,0):(canvas.width-w)*.62;ctx.drawImage(im,offsetX,(canvas.height-h)/2,w,h);lastDraw=index;stage.dataset.ready='true';canvas.dataset.frame=String(index)}
 function tick(){raf=0;if(!alive||paused||document.hidden||!visible)return;const rect=story.getBoundingClientRect(),travel=Math.max(1,story.offsetHeight-stage.offsetHeight);const p=clamp((parseFloat(getComputedStyle(stage).top)-rect.top)/travel);lastP=p;const pose=scenePose(p,mobile);desired=pose.frame;intro.style.opacity=pose.introOpacity;intro.style.transform=`translateX(${pose.introX}px) translateZ(${pose.introZ}px) rotateY(${pose.introRotate}deg)`;intro.inert=pose.introOpacity<.15;word.style.opacity=pose.wordOpacity;word.style.transform=`translate3d(${pose.wordX}px,${pose.wordY}px,${pose.wordZ}px) rotateY(${pose.wordRotate}deg) rotateZ(${-8+p*13}deg)`;outro.style.opacity=pose.outroOpacity;outro.style.transform=`translateY(${pose.outroY}px)`;stage.style.setProperty('--progress',String(p));caption.textContent=['For the curious. And the cautious.','Brave little beings. Big feelings.','A world of care. Right here.'][pose.chapter];count.textContent=`0${pose.chapter+1} / 03`;
 const nearest=cache.has(desired)?desired:[...cache.keys()].sort((a,b)=>Math.abs(a-desired)-Math.abs(b-desired))[0];if(nearest!==undefined&&nearest!==lastDraw)draw(nearest);request(desired);for(const delta of [1,-1,2,-2,3,-3,4,-4]){if(pending.size>=3)break;request(desired+delta)}}
 function queue(){if(!raf&&alive&&!paused&&!document.hidden&&visible)raf=requestAnimationFrame(tick)}
 function resize(){mobile=innerWidth<=600;const box=canvas.parentElement;const dpr=Math.min(devicePixelRatio||1,mobile?1.5:1.6);canvas.width=Math.round(box.clientWidth*dpr);canvas.height=Math.round(box.clientHeight*dpr);lastDraw=-1;queue()}
 const ro=new ResizeObserver(resize);ro.observe(canvas.parentElement);const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting;if(visible)queue();else{cancelAnimationFrame(raf);raf=0}},{rootMargin:'100px'});io.observe(story);
 const motion=()=>{paused=document.documentElement.dataset.motion==='paused';if(paused){cancelAnimationFrame(raf);raf=0;intro.inert=false}else resize()};const visibility=()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0}else queue()};window.addEventListener('scroll',queue,{passive:true});window.addEventListener('resize',resize);document.addEventListener('cat:motion',motion);document.addEventListener('visibilitychange',visibility);window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);raf=0});window.addEventListener('pageshow',queue);resize();
 return()=>{alive=false;cancelAnimationFrame(raf);ro.disconnect();io.disconnect();cache.forEach(v=>v.close());cache.clear();window.removeEventListener('scroll',queue);window.removeEventListener('resize',resize);document.removeEventListener('cat:motion',motion);document.removeEventListener('visibilitychange',visibility)};
}
